server:
  port: 8080

zuul:
  add-proxy-headers: true
  routes:
    vishnu-gateway: /**
    vishnu-gateway: http://localhost:8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/