server:
  port: 8002

eureka:
  instance:
    preferIpAddress: true

spring:
  application:
    name: vishnu-flight-monitoring-service
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://vishnu-zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0
  mongodb:
        database: "flight-monitoring"

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true

api:
  version: v1